{
 "title": "Prometheus",
 "tags": [ "monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "TSDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Persistent Volume usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}) - sum by(namespace) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "Used: {{namespace}}"
    },
    {
     "expr": "sum by(namespace) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "Free: {{namespace}}"
    }
   ]
  },
  {
   "title": "TSDB WAL storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (max_over_time(prometheus_tsdb_wal_storage_size_bytes[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB head chunks storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_chunks_storage_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB storage blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target metadata cache size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(scrape_job) (prometheus_target_metadata_cache_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Discovered targets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(max by(config) (prometheus_sd_discovered_targets), \"prefix\", \"$2\", \"config\", \"(serviceMonitor/monitoring)/(.*)\")",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Grafana dashboard GET",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(quantile) (max_over_time(grafana_api_dashboard_get_milliseconds[$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(scrape_job) (prometheus_target_scrape_pool_targets) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes work queue depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(queue_name) (prometheus_sd_kubernetes_workqueue_depth)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "min(min_over_time(prometheus_ready[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(scrape_job) (prometheus_target_scrapes_exceeded_body_size_limit_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(scrape_job) (prometheus_target_scrape_pool_exceeded_label_limits_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(scrape_job) (prometheus_target_scrapes_exceeded_sample_limit_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(job) (prometheus_target_scrape_pool_exceeded_target_limit_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(job) (prometheus_target_scrape_pool_reloads_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (sum_over_time(prometheus_engine_queries[$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus HTTP success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "max by(code, handler) (increase(prometheus_http_requests_total{code=~\"2.+\"}[$__interval])) > 0",
     "legendFormat": "{{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Prometheus HTTP failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by(code, handler) (sum_over_time(prometheus_http_requests_total{code!~\"2.+\"}[$__interval])) > 0",
     "legendFormat": "{{handler}} {{code}}"
    }
   ]
  }
 ]
}