{
 "title": "Command Center",
 "description": "Command Center\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance_shape",
    "label": "Instance Shape",
    "query": {
     "query": "label_values(node_uname_info,instance_shape)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "CPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(node) (kube_node_info))\n-\ncount(count by(node) (kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"} > 0))"
    }
   ]
  },
  {
   "title": "GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(node) (kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"} > 0))"
    }
   ]
  },
  {
   "title": "Healthy GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  node_health_status == 1\n  and on(hostname)\n  label_replace(\n    max by(node) (\n      kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"} > 0\n    ),\n    \"hostname\", \"$1\", \"node\", \"(.*)\"\n  )\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Total GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"})"
    }
   ]
  },
  {
   "title": "Healthy GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"},\n    \"hostname\", \"$1\", \"node\", \"(.*)\"\n  )\n  * on(hostname) group_left()\n  (node_health_status == 1)\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Compute Node Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_health_status\nand on(hostname)\nlabel_replace(\n  max by(node) (\n    kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"} > 0\n  ),\n  \"hostname\", \"$1\", \"node\", \"(.*)\"\n)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Historical Cluster Node Health",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_health_status\nand on(hostname)\nlabel_replace(\n  max by(node) (\n    kube_node_status_capacity{resource=~\"(amd|nvidia)_com_gpu\"} > 0\n  ),\n  \"hostname\", \"$1\", \"node\", \"(.*)\"\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Cluster Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Historical Cluster Node Issues",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "0 * label_replace(\n  max by(node, condition) (\n    kube_node_status_condition{condition=~\"CpuProfile|DcgmiHealth|GpuBadPages|GpuBus|GpuCount|GpuEcc|GpuFabricMgr|GpuImex|GpuPcie|GpuRowRemap|GpuXid|IpAddress|NodeHasPcieErrors|NvlinkSpeed|OcaVersion|RdmaLink|RdmaLinkFlapping|RdmaRttcc|RdmaVfCounters|RdmaVfRoutes|RdmaWpaAuth|Rocminfo\", status=\"true\"} == 1\n  ),\n  \"hostname\", \"$1\", \"node\", \"(.*)\"\n)\nor\n2 * label_replace(\n  max by(node, condition) (\n    kube_node_status_condition{condition=~\"CpuProfile|DcgmiHealth|GpuBadPages|GpuBus|GpuCount|GpuEcc|GpuFabricMgr|GpuImex|GpuPcie|GpuRowRemap|GpuXid|IpAddress|NodeHasPcieErrors|NvlinkSpeed|OcaVersion|RdmaLink|RdmaLinkFlapping|RdmaRttcc|RdmaVfCounters|RdmaVfRoutes|RdmaWpaAuth|Rocminfo\", status=\"unknown\"} == 1\n  ),\n  \"hostname\", \"$1\", \"node\", \"(.*)\"\n)",
     "legendFormat": "{{hostname}} / {{condition}}"
    }
   ]
  }
 ]
}